version: '3'
services:
  proxy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8080:80
    depends_on:
      - auth-api
      - auth-ui
  auth-api:
    image: stoplight/prism:4
    volumes:
      - ./:/tmp/work
    command: >
      mock -p 4010 --host 0.0.0.0
      /tmp/work/swagger/auth_api.yaml
  auth-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/auth_api.yaml
