version: '3'
services:
  proxy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
    depends_on:
      - mock-server
      - swagger-ui
  mock-server:
    image: stoplight/prism:4
    volumes:
      - ${SWAGGER_DIR:-./swagger}:/tmp/swagger
    command: >
      mock -p 4010 --host 0.0.0.0
      /tmp/swagger/api.yaml
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ${SWAGGER_DIR:-./swagger}:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/api.yaml
