openapi: 3.0.0
info:
  version: '1.0'
  title: Liberty API
servers:
  - url: /api/v1
paths:

# Config
  /configs/app:
    get:
      tags:
        - Configs
      summary: 서비스 설정값
      description: 클라이언트에서 필요한 서비스 설정값을 가져온다
      operationId: getConfigsApp
      responses:
        '200':
          description: Service Config
          content:
            application/json:
              schema:
                type: object
                properties:
                  bwAccount:
                    type: object
                    properties:
                      bankName:
                        type: string
                        description: 블루웨일 입금 계좌 은행
                        example: DBS Bank
                      accountNumber:
                        type: string
                        description: 블루웨일 입금 계좌번호
                        example: 1002-342-302953
                      accountOwner:
                        type: string
                        description: 블루웨일 입금 계좌 은행명
                        example: 블루웨일
                      swiftCode:
                        type: string
                        description: 블루웨일 계좌 swiftCode
                        example: DBSSSGSG
                      bankAddress:
                        type: string
                        description: 은행 주소
                        example: 12 Marina Boulevard, DBS Asia Central, Marina Bay Financial Centre Tower 3, Singapore 018982
                  localBankAccount:
                    type: array
                    items:
                      type: object
                      properties:
                        currency:
                          $ref: '#/components/schemas/CurrencyCode'
                        isUsed:
                          type: boolean
                          example: true
                        bankName:
                          type: string
                          example: 'DBS Bank - UK'
                        accountOwner:
                          type: string
                          example: 'Shareable Asset PL - UK'
                        accountNumber:
                          type: string
                          example: '072-022963-0'
                  showPreference:
                    type: "array"
                    items:
                      type: "string"
                    example: ["rewardBanner"]
                  otpTimeout:
                    type: "object"
                    description: "otp 기다리는 시간 timeout"
                    properties:
                      value:
                        type: integer
                        example: 120
                      timeScale:
                        type: string
                        description: "otpTimeout value에 대한 부가 설명"
                        example: "seconds (possible value: 60~120)"
                  timestamp:
                    type: integer
                    description: "server의 unix timestamp"
                    example: 1608194428984
                  timezone:
                    type: string
                    description: "Local Time Zone"
                    example: "Asia/Singapore"
                  idDocsSelectableCountries:
                    type: array
                    items:
                      type: object
                      properties:
                        countryCode:
                          type: string
                          example: KOR
                        passport:
                          type: boolean
                          example: true
                        nationalId:
                          type: boolean
                          example: true
                        drivingLicense:
                          type: boolean
                          example: true
                        residencePermit:
                          type: boolean
                          example: true
# System
  /versions:
    get:
      tags:
        - System
      summary: 지원 가능한 모바일 앱의 버전 정보를 가져온다
      description: 지원 가능한 Android와 iOS 의 minimum version, latest version 을 가져온다
      operationId: getVersions
      responses:
        '200':
          description: 지원 가능한 MobileVersion
          content:
            application/json:
              schema:
                type: object
                properties:
                  androidVersion:
                    $ref: '#/components/schemas/MobileVersion'
                  iosVersion:
                    $ref: '#/components/schemas/MobileVersion'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: liberty.sid       # cookie name
    bearerAuth:          # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 
  schemas:
    MobileVersion:
      type: object
      properties:
        minVersionCode:
          type: integer
          description: 최소 동작을 위한 mobile 버전 코드
          example: 60
        minVersionName:
          type: string
          description: 최소 동작을 위한 mobile 버전명
          example: 1.1.0
        latestVersionCode:
          type: integer
          description: 최신 mobile 버전 코드
          example: 60
        latestVersionName:
          type: string
          description: 최신 mobile 버전명
          example: 1.1.0
    CurrencyCode:
      type: string
      enum: [AUD, CAD, CHF, CNH, EUR, GBP, HKD, JPY, NZD, NOK, SEK, SGD, USD]
      description: Multi Currency 통화코드
    CountryCode:
      type: string
      enum: [AUS, CAN, CHE, CHN, EUR, GBR, HKG, JPN, NZL, NOR, SWE, SGP, USA]
