name: Validate API swagger documentation

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get OpenAPI files
      id: getfiles
      run:  |
        echo 'FILE_LIST<<EOF' >> $GITHUB_ENV
        find swagger -type f -iname "*.yaml" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: swagger-validator
      uses: mbowman100/swagger-validator-action@master
      with:
        files: ${{ env.FILE_LIST }}
    - name: upload to S3
      env:
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      run: |
        aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          swagger s3://${{ secrets.AWS_BUCKET }}
