name: Validate API swagger documentation

on: push

jobs:
  swagger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get OpenAPI files
      id: getfiles
      run:  |
        echo 'FILE_LIST<<EOF' >> $GITHUB_ENV
        find swagger -type f -iname "*.yaml" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Validate OpenAPI files
      uses: mbowman100/swagger-validator-action@master
      with:
        files: ${{ env.FILE_LIST }}
    - name: Upload OpenAPI files to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          swagger s3://${{ secrets.AWS_BUCKET }}/swagger
    - name: Deploy to Mock API Server
      uses: appleboy/ssh-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        host: ${{ secrets.MOCK_SERVER_HOST }}
        username: ${{ secrets.MOCK_SERVER_USERNAME }}
        key: ${{ secrets.MOCK_SERVER_KEY }}
        port: ${{ secrets.MOCK_SERVER_PORT }}
        envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY
        script_stop: true
        script: |
          aws s3 sync \
          s3://${{ secrets.AWS_BUCKET }}/swagger \
          ${{ secrets.MOCK_SWAGGER_DIR }}
